server:
  port: 18085
spring:
  application:
    name: search
  data:
    #ES链接配置
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#超时配置
ribbon:
  ReadTimeout: 300000 #Feign数据读取超时时间

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000