server:
  port: 18091
spring:
  application:
    name: pay
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.211.132
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
        #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE

#微信支付信息配置
weixin:
  appid: wx8397f8696b538317     #应用ID
  partner: 1473426802           # 商户号
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb    # 秘钥
  notifyurl: http://2cw4969042.wicp.vip:34488/weixin/pay/notify/url  # 回到地址

#位置支付交换机和队列  mq.pay.exchange.seckillorder  mq.pay.routing.seckillkey
mq:
  pay:
    exchange:
      order: exchange.order  #交换机
      seckillorder: exchange.seckillorder  #交换机
    queue:
      order: queue.order     #队列
      seckillorder: queue.seckillorder     #队列
    routing:
      key: queue.order    #路由key
      seckillkey: queue.seckillorder    #路由key