
spring:
  datasource:
    url: jdbc:mysql://localhost/spring?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: classpath:/mapper/*.xml

  type-aliases-package: com.java.domain
logging:

  level:
    com:
      itheima:
        mapper:
          debug

